%% MyMainScript

tic;
%% Your code here
figure(1)
myAHE('../data/TEM.png',1,5)
print('TEM_5','-dpng')
figure(2)
myAHE('../data/TEM.png',1,10)
print('TEM_10','-dpng')
figure(3)
myAHE('../data/TEM.png',1,50)
print('TEM_50','-dpng')
figure(4)
myAHE('../data/TEM.png',1,25)
print('TEM_25','-dpng')
% figure(5)
% myAHE('../data/TEM.png',1,100)
% print('TEM_100','-dpng')
% figure(6)
% myAHE('../data/TEM.png',1,150)
% print('TEM_150','-dpng')
% figure(7)
% myAHE('../data/TEM.png',1,200)
% print('TEM_200','-dpng')
% figure(8)
% myAHE('../data/TEM.png',1,250)
% print('TEM_250','-dpng')
% figure(9)
% myAHE('../data/TEM.png',1,300)
% print('TEM_300','-dpng')
% figure(10)
% myAHE('../data/TEM.png',1,350)
% figure(11)
% myAHE('../data/TEM.png',1,400)
toc;
