%% MyMainScript

tic;
%% Your code here
figure(1)
myAHE('../data/canyon.png',0,5)
print('canyon_5','-dpng')
figure(2)
myAHE('../data/canyon.png',0,10)
print('canyon_10','-dpng')
figure(3)
myAHE('../data/canyon.png',0,50)
print('canyon_50','-dpng')
figure(4)
myAHE('../data/canyon.png',0,75)
print('canyon_75','-dpng')
figure(5)
myAHE('../data/canyon.png',0,100)
print('canyon_100','-dpng')
figure(6)
myAHE('../data/canyon.png',0,150)
print('canyon_150','-dpng')
figure(7)
myAHE('../data/canyon.png',0,200)
print('canyon_200','-dpng')
figure(8)
myAHE('../data/canyon.png',0,250)
print('canyon_250','-dpng')
figure(9)
myAHE('../data/canyon.png',0,300)
print('canyon_300','-dpng')
% figure(10)
% myAHE('../data/canyon.png',0,350)
% figure(11)
% myAHE('../data/canyon.png',0,400)
toc;
